# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27b134ba5848b3d6409e7b30234af8cbfa38f7d1ebda8a6d557684d845d56d86690ddea8c25c1407b37f9bc7824db4e8ede5270243cee7f2efe7c52a97c8670a

test:
  secret_key_base: 29ad2ef10d135b5261cd79442bfd8208feeb860e78edd0f1ec011efab7acb8926d221f927c5605fbbc31cba1ed5ec52c923d056e1824b1acf9dd84306aa2631e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
